import { expect, test } from '@playwright/test'
import type { Page } from '@playwright/test'

const detail = '/expedientes/DEMO-2026-0010'
test.beforeEach(async ({ page }) => {
  await page.goto('/login')
  await page.getByRole('button', { name: 'Continuar con Google' }).click()
  await expect(page).toHaveURL(/\/inicio$/)
})

async function resolution(page: Page) {
  await page.goto(`${detail}?seccion=resoluciones`)
  await page.getByLabel(/^Número de resolución/).fill('RES-DEMO-TEST')
  await page.getByLabel('Tipo de resolución').selectOption('Otro')
  await page.getByLabel('Referencia de archivo PDF').setInputFiles({ name: 'prueba.pdf', mimeType: 'application/pdf', buffer: Buffer.from('%PDF-1.4 mock') })
  await page.getByRole('button', { name: 'Guardar resolución' }).click()
  await expect(page.getByRole('status')).toContainText('Resolución guardada')
}

test('resoluciones vinculadas, asesor, jurado y búsqueda persisten al recargar', async ({ page }) => {
  await resolution(page)
  await page.getByRole('link', { name: 'Asesor y jurado', exact: true }).click()
  await page.getByLabel('Docente asesor', { exact: true }).selectOption('DOC-001')
  await page.getByLabel('Resolución asociada').nth(0).selectOption({ label: 'RES-DEMO-TEST · Otro' })
  await page.getByRole('button', { name: 'Guardar asesor' }).click()
  await expect(page.getByRole('status')).toContainText('Asesor guardado')
  await page.getByLabel('Presidente', { exact: true }).selectOption('DOC-002')
  await page.getByLabel('Secretario', { exact: true }).selectOption('DOC-002')
  await page.getByLabel('Resolución asociada').nth(1).selectOption({ label: 'RES-DEMO-TEST · Otro' })
  await page.getByRole('button', { name: 'Guardar jurado' }).click()
  await expect(page.getByRole('alert')).toContainText('dos cargos')
  await page.getByLabel('Secretario', { exact: true }).selectOption('DOC-003')
  await page.getByRole('button', { name: 'Guardar jurado' }).click()
  await expect(page.getByRole('status')).toContainText('Jurado guardado')
  await page.reload()
  await expect(page.getByLabel('Docente asesor', { exact: true })).toHaveValue('DOC-001')
  await expect(page.getByLabel('Secretario', { exact: true })).toHaveValue('DOC-003')
  await page.getByRole('link', { name: 'Resoluciones', exact: true }).click()
  await expect(page.getByText(/Referencia PDF: prueba.pdf/)).toBeVisible()
  await page.getByRole('button', { name: 'Editar resolución RES-DEMO-TEST' }).click()
  await page.getByLabel('Tipo de resolución').selectOption('Asesor')
  await page.getByRole('button', { name: 'Guardar resolución' }).click()
  await expect(page.getByRole('alert')).toContainText('El jurado necesita')
  await page.getByLabel('Tipo de resolución').selectOption('Otro')
  await page.getByLabel(/^Número de resolución/).fill('RES-ACTUALIZADA')
  await page.getByRole('button', { name: 'Guardar resolución' }).click()
  await page.goto('/expedientes')
  await page.getByLabel('Buscar expediente').fill('RES-ACTUALIZADA')
  await expect(page.getByRole('status')).toHaveText('1–1 de 1 registros')
  await page.getByLabel('Buscar expediente').fill('Elena Vargas')
  await expect(page.getByRole('status')).toHaveText('1–1 de 1 registros')
})

test('registrar y editar un resultado de sorteo externo sin asignar jurado', async ({ page }) => {
  await resolution(page)
  await page.getByRole('link', { name: 'Sorteos externos', exact: true }).click()
  await page.getByLabel('Resolución asociada').selectOption({ label: 'RES-DEMO-TEST · Otro' })
  await page.getByRole('button', { name: 'Guardar resultado de sorteo' }).click()
  await expect(page.getByRole('alert')).toContainText('Selecciona los docentes')
  await page.getByRole('checkbox', { name: /Elena Vargas/ }).check()
  await page.getByRole('checkbox', { name: /Rafael Montes/ }).check()
  await page.getByRole('button', { name: 'Guardar resultado de sorteo' }).click()
  await expect(page.getByRole('status')).toContainText('guardado')
  await page.reload()
  await page.getByRole('button', { name: /Editar sorteo del/ }).click()
  await expect(page.getByRole('checkbox', { name: /Elena Vargas/ })).toBeChecked()
  await page.getByRole('checkbox', { name: /Rafael Montes/ }).uncheck()
  await page.getByRole('button', { name: 'Guardar resultado de sorteo' }).click()
  await expect(page.getByRole('status')).toContainText('guardado')
  await page.getByRole('link', { name: 'Asesor y jurado', exact: true }).click()
  await expect(page.getByLabel('Presidente', { exact: true })).toHaveValue('')
})

test('sustentación valida fechas y actualiza indicadores sin perderse al editar', async ({ page }) => {
  await page.goto(`${detail}?seccion=sustentacion`)
  await page.getByLabel('Fecha de sustentación').fill('2099-01-01')
  await page.getByLabel('Resultado de sustentación').selectOption('Aprobado')
  await page.getByRole('button', { name: 'Guardar sustentación' }).click()
  await expect(page.getByRole('alert')).toContainText('futura')
  await page.getByLabel('Fecha de sustentación').fill('2026-09-20')
  await page.getByRole('button', { name: 'Guardar sustentación' }).click()
  await expect(page.getByRole('status')).toContainText('Sustentación guardada')
  await page.getByRole('link', { name: 'Editar expediente' }).click()
  await page.getByLabel('Fecha de inicio').fill('2026-09-25')
  await page.getByRole('button', { name: 'Guardar cambios' }).click()
  await expect(page.getByRole('alert')).toContainText('sustentación')
  await page.getByLabel('Fecha de inicio').fill('2026-03-12')
  await page.getByRole('button', { name: 'Guardar cambios' }).click()
  await page.goto('/inicio')
  await expect(page.getByRole('region', { name: 'Indicadores de expedientes' }).locator('dd')).toHaveText(['10', '6', '2', '5'])
  await page.goto(`${detail}?seccion=sustentacion`)
  await page.reload()
  await expect(page.getByLabel('Resultado de sustentación')).toHaveValue('Aprobado')
  await page.getByLabel('Resultado de sustentación').selectOption('Pendiente')
  await page.getByRole('button', { name: 'Guardar sustentación' }).click()
  await page.goto('/inicio')
  await expect(page.getByRole('region', { name: 'Indicadores de expedientes' }).locator('dd')).toHaveText(['10', '6', '2', '4'])
})

test('secciones académicas se adaptan a móvil y escritorio', async ({ page }, testInfo) => {
  for (const section of ['asignaciones', 'resoluciones', 'sorteos', 'sustentacion']) {
    await page.goto(`${detail}?seccion=${section}`)
    for (const width of [320, 390, 1440]) {
      await page.setViewportSize({ width, height: 1000 })
      await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      if (width !== 320) await page.screenshot({ path: testInfo.outputPath(`${section}-${width}.png`), fullPage: true })
    }
  }
})
