import { expect, test } from '@playwright/test'

test.beforeEach(async ({ page }) => {
  await page.goto('/login')
  await page.getByRole('button', { name: 'Continuar con Google' }).click()
  await expect(page).toHaveURL(/\/inicio$/)
})

test('buscar docentes, filtrar escuelas y consultar un historial vacío', async ({ page }, testInfo) => {
  await page.goto('/docentes')
  await page.getByLabel('Buscar docente').fill('hector')
  await expect(page.getByRole('heading', { name: 'Héctor Salinas' })).toBeVisible()
  await expect(page.getByRole('status')).toHaveText('1 docentes encontrados')
  await page.getByLabel('Escuela del docente').selectOption('Educación')
  await expect(page.getByRole('heading', { name: 'No se encontraron docentes' })).toBeVisible()
  await page.getByRole('button', { name: 'Limpiar filtros' }).click()
  await expect(page.getByRole('status')).toHaveText('8 docentes encontrados')
  for (const route of ['/docentes', '/docentes/DOC-001']) {
    await page.goto(route)
    for (const width of [320, 390, 1440]) {
      await page.setViewportSize({ width, height: 1000 })
      await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
      if (width === 390 || width === 1440) await page.screenshot({ path: testInfo.outputPath(`${route.replaceAll('/', '-')}-${width}.png`), fullPage: true })
    }
  }
  await expect(page.getByRole('heading', { name: 'Sin participaciones registradas' })).toBeVisible()
  await page.goto('/docentes/NO-EXISTE')
  await expect(page.getByRole('heading', { name: 'No encontramos este docente' })).toBeVisible()
  await page.getByRole('link', { name: 'Volver a docentes' }).click()
  await expect(page).toHaveURL(/\/docentes$/)
})

test('el historial refleja asesorías, cargos y resoluciones del expediente', async ({ page }, testInfo) => {
  await page.goto('/expedientes/DEMO-2026-0010?seccion=resoluciones')
  await page.getByLabel(/^Número de resolución/).fill('RES-HISTORIAL-001')
  await page.getByLabel('Tipo de resolución').selectOption('Otro')
  await page.getByRole('button', { name: 'Guardar resolución' }).click()
  await expect(page.getByRole('status')).toContainText('Resolución guardada')
  await page.getByRole('link', { name: 'Asesor y jurado', exact: true }).click()
  await page.getByLabel('Docente asesor', { exact: true }).selectOption('DOC-001')
  await page.getByLabel('Resolución asociada').nth(0).selectOption({ label: 'RES-HISTORIAL-001 · Otro' })
  await page.getByRole('button', { name: 'Guardar asesor' }).click()
  await page.getByLabel('Presidente', { exact: true }).selectOption('DOC-002')
  await page.getByLabel('Resolución asociada').nth(1).selectOption({ label: 'RES-HISTORIAL-001 · Otro' })
  await page.getByRole('button', { name: 'Guardar jurado' }).click()
  await expect(page.getByRole('status')).toContainText('Jurado guardado')
  await page.goto('/docentes/DOC-001')
  await expect(page.getByRole('table')).toContainText('Asesor')
  await expect(page.getByRole('link', { name: 'RES-HISTORIAL-001', exact: true })).toBeVisible()
  await page.getByLabel('Participación', { exact: true }).selectOption('Jurado')
  await expect(page.getByRole('heading', { name: 'Sin participaciones para estos filtros' })).toBeVisible()
  await page.getByRole('button', { name: 'Limpiar filtros' }).click()
  await page.getByLabel('Año de resolución').selectOption('2026')
  await expect(page.getByRole('table')).toContainText('Lucía Paredes')
  await page.goto('/docentes/DOC-002')
  await page.reload()
  await expect(page.getByRole('table')).toContainText('Jurado · Presidente')
  for (const width of [320, 1440]) {
    await page.setViewportSize({ width, height: 1000 })
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await page.screenshot({ path: testInfo.outputPath(`historial-${width}.png`), fullPage: true })
  }
  await page.getByRole('link', { name: 'RES-HISTORIAL-001', exact: true }).click()
  await expect(page).toHaveURL(/seccion=resoluciones$/)
  await page.getByRole('button', { name: 'Editar resolución RES-HISTORIAL-001' }).click()
  await page.getByLabel(/^Número de resolución/).fill('RES-HISTORIAL-EDITADA')
  await page.getByRole('button', { name: 'Guardar resolución' }).click()
  await expect(page.getByRole('status')).toContainText('Resolución guardada')
  await page.goto('/docentes/DOC-002')
  await expect(page.getByRole('table')).toContainText('RES-HISTORIAL-EDITADA')
  await page.getByRole('link', { name: 'DEMO-2026-0010', exact: true }).click()
  await page.getByLabel('Presidente', { exact: true }).selectOption('DOC-003')
  await page.getByRole('button', { name: 'Guardar jurado' }).click()
  await expect(page.getByRole('status')).toContainText('Jurado guardado')
  await page.goto('/docentes/DOC-002')
  await expect(page.getByRole('heading', { name: 'Sin participaciones registradas' })).toBeVisible()
  await page.goto('/docentes/DOC-003')
  await expect(page.getByRole('table')).toContainText('Jurado · Presidente')
})
